--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Taylor-pm-pl/SimplySickles
build-by-default: true
branches:
- stable
projects:
  SimplySickles:
    path: ""
    icon: icon.png
    libs:
      - src: jasonw4331/libCustomPack/libCustomPack
        version: ^1.0.0
...
