--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Taylor-pm-pl/SimplySickles
build-by-default: true
branches:
- API-4
- API-5
projects:
  SimplySickles:
    path: ""
    icon: icon.png
    libs:
      - src: jasonw4331/libCustomPack/libCustomPack
        version: ^1.0.0
    lint:
      phpstan: false
...
