name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-php:
    name: Prepare PHP
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ubuntu-20.04]
        php: ["8.1", "8.2"]

    steps:
      - name: Build and prepare PHP cache
        uses: pmmp/setup-php-action@3.1.0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"

  phpstan:
    name: PHPStan analysis
    needs: build-php
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: ["8.1", "8.2"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: pmmp/setup-php-action@2.0.0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: "5"

      - name: Restore Composer package cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress --memory-limit=2G

  codestyle:
    name: Code Style checks
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: 8.0
          tools: php-cs-fixer:3.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff --ansi
